import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "./query/QueryProvider";
import { QueryClient } from "@tanstack/react-query";
import Header from "@/components/layout/Header";
import TopButton from "./components/topbutton/TopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <Header />
          {children}
          <TopButton />
        </QueryProvider>
      </body>
    </html>
  );
}
